module.exports = {
	plugins: ["vuejs-accessibility"],
	extends: ["plugin:vuejs-accessibility/recommended"],
	rules: {
		"vue/block-tag-newline": "error",
		"vue/component-name-in-template-casing": "error",
		"vue/custom-event-name-casing": ["error", "camelCase"],
		"vue/html-button-has-type": "error",
		"vue/html-comment-content-newline": "error",
		"vue/html-comment-content-spacing": "error",
		"vue/html-comment-indent": "error",
		"vue/match-component-file-name": [
			"error",
			{ extensions: ["vue"], shouldMatchCase: true },
		],
		"vue/next-tick-style": "error",
		"vue/no-bare-strings-in-template": "error",
		"vue/no-boolean-default": "error",
		"vue/no-duplicate-attr-inheritance": "error",
		"vue/no-empty-component-block": "error",
		"vue/no-invalid-model-keys": "error",
		"vue/no-multiple-objects-in-class": "error",
		"vue/no-potential-component-option-typo": [
			"error",
			{ presets: ["vue", "vue-router"] },
		],
		"vue/no-reserved-component-names": [
			"error",
			{
				disallowVueBuiltInComponents: true,
				disallowVue3BuiltInComponents: true,
			},
		],
		"vue/no-restricted-call-after-await": [
			"error",
			{ module: "vue-i18n", path: "useI18n" },
		],
		"vue/no-restricted-component-options": [
			"error",
			"init",
			"beforeCompile",
			"compiled",
			"activate",
			"ready",
			"/^(?:at|de)tached$/",
			["props", "*", "twoWay"],
		],
		"vue/no-restricted-v-bind": [
			"error",
			{
				argument: "/^v-/",
				message:
					"Using `:v-xxx` is not allowed. Instead, remove `:` and use it as directive.",
			},
		],
		"vue/no-static-inline-styles": ["error", { allowBinding: true }],
		"vue/no-template-target-blank": "error",
		"vue/no-this-in-before-route-enter": "error",
		"vue/no-undef-properties": "error",
		"vue/no-undef-components": [
			"error",
			{ ignorePatterns: ["router-view", "router-link"] },
		],
		"vue/no-unsupported-features": ["error", { version: "~3.2.0" }],
		"vue/no-unused-properties": [
			"error",
			{
				groups: ["props", "data", "computed", "methods", "setup"],
				deepData: true,
				ignorePublicMembers: true,
			},
		],
		"vue/no-unused-refs": "error",
		"vue/no-use-computed-property-like-method": "error",
		"vue/no-useless-mustaches": "error",
		"vue/no-useless-v-bind": "error",
		"vue/no-v-text": "error",
		"vue/padding-line-between-blocks": "error",
		"vue/require-direct-export": "error",
		"vue/require-emit-validator": "error",
		"vue/require-name-property": "error",
		"vue/script-indent": "error",
		"vue/v-for-delimiter-style": "error",
		"vue/v-on-function-call": "error",
	},
};
